# Generated by Django 5.0 on 2023-12-13 12:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('action', models.CharField(max_length=100)),
                ('deliverables', models.CharField(max_length=100)),
                ('impact', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('resources', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('accountability', models.CharField(max_length=100)),
                ('timeframe', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCategory1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('phone', models.CharField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('name_of_ceo_md', models.CharField(blank=True, max_length=100, null=True)),
                ('company_contacts_numbers', models.TextField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('official_social_media_pages', models.TextField(blank=True, null=True)),
                ('legal_formation', models.TextField(blank=True, null=True)),
                ('ownership', models.TextField(blank=True, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('sales_channels', models.TextField(blank=True, null=True)),
                ('professional_staff', models.CharField(blank=True, max_length=100, null=True)),
                ('exports_of_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('management', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_classification', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('web_search', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_industry_references', models.CharField(blank=True, max_length=100, null=True)),
                ('official_governmental_websites', models.CharField(blank=True, max_length=100, null=True)),
                ('recent_strategy_or_planning_document', models.TextField(blank=True, null=True)),
                ('direction_strategy', models.TextField(blank=True, null=True)),
                ('initiatives_projects', models.TextField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('financial', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_chain', models.CharField(blank=True, max_length=100, null=True)),
                ('organizational_people', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('legal', models.CharField(blank=True, max_length=100, null=True)),
                ('technological', models.CharField(blank=True, max_length=100, null=True)),
                ('headcount', models.IntegerField(blank=True, null=True)),
                ('headcount_distribution', models.CharField(blank=True, max_length=100, null=True)),
                ('headcount_distribution_notes', models.TextField(blank=True, null=True)),
                ('turnover', models.CharField(blank=True, max_length=100, null=True)),
                ('headcount_classifications', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actionplanform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_admin.actionplanform')),
                ('attachments', models.ManyToManyField(blank=True, related_name='company_attachments', to='hr_admin.attachment')),
                ('consultant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulting_companies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('evaluationform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationform')),
                ('companyinputs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputsform')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_attachments', to='hr_admin.company'),
        ),
        migrations.CreateModel(
            name='EvaluationCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('EvaluationCategory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationcategory1')),
            ],
        ),
        migrations.AddField(
            model_name='actionplanform',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationcategory2'),
        ),
        migrations.AddField(
            model_name='evaluationcategory1',
            name='EvaluationForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationform'),
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('EvaluationCategory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationcategory2')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluationform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.evaluationform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('InputsForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputsform')),
            ],
        ),
        migrations.CreateModel(
            name='InputsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('options', models.CharField(blank=True, choices=[('yes_no', 'Yes or No'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputscategory')),
            ],
        ),
        migrations.CreateModel(
            name='InputsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('NA', 'N/A'), ('Y', 'Yes'), ('N', 'No')], default='NA', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.company')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.inputsquestion')),
            ],
            options={
                'unique_together': {('company', 'question')},
            },
        ),
    ]
