# Generated by Django 5.0 on 2023-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('consultant', 'Consultant')], default='company', max_length=20),
        ),
    ]
