# Generated by Django 4.2.7 on 2023-12-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_admin.category'),
        ),
    ]
