# Generated by Django 5.0 on 2023-12-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0004_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_admin.company'),
            preserve_default=False,
        ),
    ]
