# Generated by Django 4.2.7 on 2023-12-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0004_inputsanswer_inputscategory_inputsquestion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationquestion',
            old_name='category',
            new_name='EvaluationCategory2',
        ),
        migrations.RemoveField(
            model_name='evaluationquestion',
            name='EvaluationForm',
        ),
    ]
