# Generated by Django 4.2.7 on 2023-12-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0005_rename_category_evaluationquestion_evaluationcategory2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationquestion',
            name='weight',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputsanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inputsanswer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputsform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputsquestion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
