# Generated by Django 5.0 on 2023-12-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0005_remove_evaluationanswer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationanswer',
            old_name='EvaluationQuestion',
            new_name='question',
        ),
    ]
