# Generated by Django 5.0 on 2023-12-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
