# Generated by Django 5.0 on 2023-12-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0008_alter_inputsanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputsanswer',
            old_name='InputsQuestion',
            new_name='question',
        ),
    ]
