# Generated by Django 5.0 on 2023-12-05 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0009_rename_inputsquestion_inputsanswer_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='consultant',
        ),
        migrations.AddField(
            model_name='company',
            name='consultant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consulting_companies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
